apiVersion: apps/v1
kind: Deployment
metadata:
  name: typescript
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typescript
  template:
    metadata:
      labels:
        app: typescript
        tier: frontend
    spec:
      containers:
      - name: typescript
        image: gitargocd.jfrog.io/typescript/image:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: actions

